version: '3.2'

services:
  es01:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch01:/usr/share/elasticsearch/data:z
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - ELASTIC_PASSWORD=changeme
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es02,es03 
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    deploy: 
      mode: replicated 
      replicas: 1
      placement: 
        constraints: 
          - "node.hostname==manager-01"

  es02:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch02:/usr/share/elasticsearch/data:z
    ports:
      - "9201:9200"
      - "9301:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - ELASTIC_PASSWORD=changeme
      - node.name=es01
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    deploy: 
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - "node.hostname==manager-02"

  es03:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,z
      - elasticsearch03:/usr/share/elasticsearch/data:z
    ports:
      - "9202:9200"
      - "9302:9300"
    environment:
      - "ES_JAVA_OPTS=-Xmx256m -Xms256m"
      - ELASTIC_PASSWORD=changeme
      - node.name=es03
      - cluster.name=docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - "node.hostname==manager-03"

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,z
    ports:
      - "5044:5044"
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03
      - filebeat
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - "node.hostname==manager-03"

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,z
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - es01
      - es02 
      - es03
    deploy:
      mode: replicated
      replicas: 1
      placement: 
        constraints: 
          - "node.hostname==manager-01"

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch01:
    driver: local
  elasticsearch02:
    driver: local
  elasticsearch03:
    driver: local


